server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute 
          uri: http://localhost:8082/
          predicates: 
            - Path=/movies/**
        - id: catalogRoute 
          uri: http://localhost:8084/ 
          predicates: 
            - Path=/catalog/**
        - id: seriesRoute 
          uri: http://localhost:8086/ 
          predicates: 
            - Path=/series/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
