server:
  port: 8761

spring:
  application:
    name: eureka-service
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
