
server:
  port: 8888
spring:
  application:
    name: config-service
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
  cloud:
    config:
      server:
        git:
          uri: https://github.com/svbri/beii-final
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
